yaml

name:

Build Android APK

on:

push: branches: \[ "main" \]

jobs:

build:

runs-on: ubuntu-latest steps:

uses: actions/checkout@v3

- name: set up JDK 17

uses: actions/setup@v3

with:

java-version: '17' distribution: 'temurin'

- name: Build Gradle run: ./gradlew assembleDebug

- name: Upload APK uses: actions/upload
with:
-artifact@v3

name: app-debug path: app/build/outputs/apk/ debug/app-debug.apk
